# docker compose --env-file .env.x up
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - "${ENV_FILE}"
    ports:
      - "${UVICORN_SERVER__PORT}:${UVICORN_SERVER__PORT}"
    volumes:
      - .:/app
    restart: on-failure
    depends_on:
      - redis

  redis:
    image: docker.arvancloud.ir/redis:6-alpine
    command: redis-server --appendonly yes --requirepass ${REDIS__PASSWORD} --port ${REDIS__PORT}
    environment:
      - REDIS_PASSWORD=${REDIS__PASSWORD}
    ports:
      - "${REDIS__PORT}:${REDIS__PORT}"
    volumes:
      - ./redis_data:/data
    restart: unless-stopped
